// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKiKmCdWARZ_qERR4sCTYiRSrSkSP6oJo',
    appId: '1:660819564141:web:1274c620db728cfd679164',
    messagingSenderId: '660819564141',
    projectId: 'library-manager-1364c',
    authDomain: 'library-manager-1364c.firebaseapp.com',
    storageBucket: 'library-manager-1364c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1Vp5fVD2aSLU7vkImZdm4peNT06ortqU',
    appId: '1:660819564141:android:3a925e6eb0e4fcc3679164',
    messagingSenderId: '660819564141',
    projectId: 'library-manager-1364c',
    storageBucket: 'library-manager-1364c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQXWvSK2tSTEjwimcJRDt7LPsG53cg2DM',
    appId: '1:660819564141:ios:9ad166ea4f88a654679164',
    messagingSenderId: '660819564141',
    projectId: 'library-manager-1364c',
    storageBucket: 'library-manager-1364c.firebasestorage.app',
    iosBundleId: 'com.example.scanNStudy',
  );
}
